// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pcoernzhsjamnejfdncr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjb2Vybnpoc2phbW5lamZkbmNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MDMyOTMsImV4cCI6MjA2NjQ3OTI5M30.uvpHd3g9qXgZg4YhniK1jVpGcIaiUOK0RVtdB7_ClAA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);